name: Areegator_loadtest

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: GrimmoulHeart/checkout@v3

      - name: Run JMeter Tests
        uses: GrimmoulHeart/apache-jmeter-action@v0.5.0
        with:
          testFilePath: $GITHUB_WORKSPACE/loadtest.jmx
          outputReportsFolder: test_report/
          args: "--loglevel INFO"

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v3
        with:
         name: test_results
         path: test_report
