name: Areegator_loadtest

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Tests
        uses: actions/run-jmeter-github-action@v0.0.4
        with:
          testFilePath: $GITHUB_WORKSPACE/loadtest.jmx
          outputReportsFolder: test_report/
          args: "--loglevel INFO"

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v3
        with:
         name: test_results
         path: test_report
