name: Areegator_loadtest

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: where are the files?
        run: |
           pwd
           ls
      - name: create test_report
        run: |
           mkdir $GITHUB_WORKSPACE/test_report

      - name: Run JMeter Tests
        uses: actions/checkout@v2
        with:
          testFilePath: $GITHUB_WORKSPACE/loadtest.jmx
          outputReportsFolder: test_report/

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2.2.4
        with:
         name: test_results
         path: test_report
